Jwt token
JohnGrey17/bookStore pull request #12
Opened 2024-05-14 00:15 UTC by JohnGrey17

2024-05-14 12:39 UTC, d1sam requested changes
Good job, but there are some minor changes, that should be done according my comments.

2024-05-14 12:39 UTC, d1sam commented on src/main/java/org/example/bookstore/dto/userdto/UserLoginRequestDto.java
> +        String email,
what about the size of an email?

2024-05-14 12:39 UTC, d1sam commented on src/main/java/org/example/bookstore/security/JwtAuthenticationFilter.java
> +
```suggestion
```

2024-05-14 12:39 UTC, d1sam commented on src/main/java/org/example/bookstore/security/JwtAuthenticationFilter.java
> +        return null;
please avoid magic numbers and string literals

2024-05-14 12:39 UTC, d1sam commented on src/main/resources/application.properties
> +jwt.secret=bigmateacedemysecretfeb24blablablablablaoiuluzichervonakaluna`
let's provide these values from env properties

2024-05-15 10:38 UTC, vovasalyha approved these changes

2024-05-15 16:06 UTC, merged