Add category model
JohnGrey17/bookStore pull request #16
Opened 2024-05-17 00:46 UTC by JohnGrey17

2024-05-17 13:19 UTC, kaiiiseeel requested changes
Looks good, left some minor comments, take a look please!

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
Just a suggestion, you can use "hasAnyRole('USER', 'ADMIN')"

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/mapper/BookMapper.java
> +    }
I think, we should set categories to ResponseDto, not RequestDto. Also, can't categories in book be null? Maybe we should validate it and set empty list if it's null?

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
I can be wrong, but isn't CascadeType.ALL bad idea?

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +    }
I think you forgot to use it
```suggestion
    @Override
    public List<BookResponseDto> getBookDtoByCategoryId(Long id, Pageable pageable) {
        return bookRepository
                .findByCategoriesId(id, pageable)
                .stream()
                .map(bookMapper::toDto)
                .toList();
    }
```

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +    }
Here you also don't use pageable
```suggestion
    @Override
    public List<CategoryDto> findAll(Pageable pageable) {
        return categoryRepository
                .findAll(pageable)
                .stream()
                .map(categoryMapper::toDto)
                .toList();
    }
```

2024-05-17 13:19 UTC, kaiiiseeel commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +        existingCategory.setDescription(requestDto.getDescription());
You have mapper for it

2024-05-21 12:58 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/dto/categorydto/CategoryRequestDto.java
> +    private String description;
Please add max length constraints to align with db constraints

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/mapper/BookMapper.java
> +
```suggestion
```

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany(fetch = FetchType.LAZY)
```

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/model/Book.java
> +    private Set<Category> categories;
Please exclude this field from equals and hashCode

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +                .collect(Collectors.toSet());
This code makes N requests to db, it could cause significant performance issues, please investigate how performance could be improved

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +        categoryRepository.findById(id)
This code returns some value that ignored, better to change this validation to 'existsById'

2024-05-21 12:58 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +                        "can`t find category by id: " + id));
Code duplication

2024-05-21 14:04 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/dto/categorydto/CategoryRequestDto.java
> +    private String name;
Please add constraint for name as well

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +            categoryIds.removeAll(foundCategoryIds);
```suggestion
```

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +        Set<Long> categoryIds = new HashSet<>(requestDto.getCategoryIds());
```suggestion

```

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +        List<Category> categories = categoryRepository.findCategoriesByIds(categoryIds);
```suggestion
        List<Category> categories = categoryRepository.findCategoriesByIds(requestDto.getCategoryIds());
```

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +            categoryIds.removeAll(foundCategoryIds);
Move thos logic to method

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/book/BookServiceImpl.java
> +        book.setCategories(new HashSet<>(categories));
I think this should work with id`s as well

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/category/CategoryService.java
> +
```suggestion
```

2024-05-21 14:04 UTC, andrii-hoienko commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +        }
Move this ti separate method and reuse on update

2024-05-22 08:54 UTC, yevheniisynytsia requested changes
Almost done, left minor comments

2024-05-22 08:54 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/model/Book.java
> +    @HashCodeExclude
wrong annotations
please use 
`@ToString.Exclude`
`@EqualsAndHashCode.Exclude`

also, you don't have `@EqualsAndHashCode` annotation, so either remove excluding or better add equals and hashcode annotation

2024-05-22 08:54 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/category/CategoryServiceImpl.java
> +                        "can`t find category by id: " + id));
`checkCategoryExists()` can be reused here

2024-05-22 10:47 UTC, merged