Add shopping cart model
JohnGrey17/bookStore pull request #17
Opened 2024-05-21 22:57 UTC by JohnGrey17

2024-05-22 10:10 UTC, HAIOVYI approved these changes
GJ

2024-05-23 09:13 UTC, yevheniisynytsia requested changes
Great job! Left some comments

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/controller/ShoppingCartController.java
> +    public void deleteCartItemById(@PathVariable Long cartItemId) {
```suggestion
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    public void deleteCartItemById(@PathVariable Long cartItemId) {
```

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/dto/cartitemdto/CartItemUpdateDto.java
> +}
![image](https://github.com/JohnGrey17/bookStore/assets/77681963/58191615-5fe4-41bb-9456-a7b47ffdf0b3)

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/mapper/CartItemMapper.java
> +    @Mapping(target = "bookId", source = "book", qualifiedByName = "bookIdByBook")
```suggestion
    @Mapping(target = "bookId", source = "book.id")
```
this should work

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/mapper/CartItemMapper.java
> +    @Mapping(target = "bookTitle", source = "book", qualifiedByName = "getTitleByBook")
```suggestion
    @Mapping(target = "bookTitle", source = "book.title")
```

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
EAGER is a bad solution. Let's remember how to use LAZY and save its efficiency

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/model/Book.java
>      private String description;
please add `@EqualsAndHashCode` to your entities

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    public ShoppingCartResponseDto getUserShoppingCartById(Long userId, Pageable pageable) {
I think you don't need `Pageable` here

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    ShoppingCart findShoppingCartByUserId(@Param("userId") Long userId);
should be `Optional<ShoppingCart>`

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(shoppingCartByUserId);
there should be a `null` check

2024-05-23 09:13 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +        }
you can move this logic into a private method and reuse in `getUserShoppingCartById`

2024-05-24 09:17 UTC, yevheniisynytsia approved these changes

2024-05-24 09:17 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +                        + "can`t by id: " + userId));
this code is duplicated

2024-05-24 09:17 UTC, yevheniisynytsia commented on src/main/java/org/example/bookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +                        + userId));
this code is duplicated

2024-05-28 23:07 UTC, closed without merging