Hw 2 solution dto
JohnGrey17/bookStore pull request #2
Opened 2024-04-23 14:39 UTC by JohnGrey17

2024-04-23 15:48 UTC, fedaktaras commented on src/main/java/org/example/bookstore/controller/BookControllerImpl.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping(value = "/api/books")
```
GET: /api/books (Retrieve book catalog) In task description

2024-04-23 15:52 UTC, fedaktaras commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        return booksOptional
```suggestion
       return  bookRepository.findAll();
```
It will be empty list if there is no books

2024-04-23 15:58 UTC, fedaktaras commented on src/main/java/org/example/bookstore/repository/impl/BookRepositoryImpl.java
> +            return entityManager.find(Book.class,id);
This way is much better that I used. now have to change)

2024-04-23 15:59 UTC, fedaktaras requested changes
Great job. Minor changes required.

2024-04-23 16:01 UTC, fedaktaras commented on src/main/java/org/example/bookstore/service/impl/BookServiceImpl.java
> +        return booksOptional
> It will be empty list if there is no books

You have to return BookDTO

2024-04-24 09:08 UTC, karma-o reviewed
just a few very minor comments

2024-04-24 09:08 UTC, karma-o commented on src/main/java/org/example/bookstore/dto/BookDto.java
> +public class BookDto {
check this discussion: https://mate.academy/chats/43264?selectedMessageId=2276366&threadId=2276235

2024-04-24 09:08 UTC, karma-o commented on src/main/java/org/example/bookstore/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
same here

2024-04-24 10:19 UTC, merged