Readme
JohnGrey17/bookStore pull request #20
Opened 2024-05-28 23:04 UTC by JohnGrey17

2024-05-30 10:23 UTC, yevheniisynytsia requested changes

2024-05-30 10:23 UTC, yevheniisynytsia commented on README.md
> +Body
I would also like to see a part about challenges that you've faced during development and how you overcame those. Also you may add some possible improvements part

2024-05-30 10:23 UTC, yevheniisynytsia commented on README.md
> +- **PATCH /api/orders/{id}** : Change the status of an order** (admin only)
let's also include a "real" env file with some mock data so that it is easily created.
You can use you env file but with removed password

2024-05-30 10:23 UTC, yevheniisynytsia commented on README.md
> +- **GET /api/orders/{orderId}/items/{itemId}**: Get detailed information about a specific order item
please add instruction how to run your project

2024-06-10 22:02 UTC, JohnGrey17 commented
Have a question can we put gif on the top of Readme ?
and could it be Mr.Bean))

2024-06-11 13:32 UTC, andrii-hoienko requested changes
Ver nice, left some minor comments

2024-06-11 13:32 UTC, andrii-hoienko commented on README.md
> +- CustomGlobalExceptionHandler for error handling
Add some description to technologies, how you used them? for what purpose?

2024-06-11 13:32 UTC, andrii-hoienko commented on README.md
> +<a href="#content-of-presentation"><img src="Logo/back.png" width="20" height="20"></a>
I don`t see video presentation as well as link to your linkedIn, you can add this in contribution section

2024-06-17 16:05 UTC, merged